"""
Gymnasium Environment for Roblox Sword Fight Bot
Connects the game state to the SB3 PPO algorithm.
"""
import gymnasium as gym
from gymnasium import spaces
import numpy as np
import time
import torch

from feature_extraction.screen_processor import ScreenCapture
from feature_extraction.color_detector import GameDetector
from feature_extraction.feature_engineer import FeatureEngineer
from utils.input_control import InputController

class RobloxGymEnv(gym.Env):
    """
    Standardized Gymnasium environment for Roblox live RL training.
    """
    def __init__(self, config: dict, checkpoint_path: str):
        super(RobloxGymEnv, self).__init__()
        
        self.config = config
        
        # Core components
        self.screen_capture = ScreenCapture(
            resolution=tuple(config.get('capture', {}).get('resolution', [800, 600])),
            fps=config.get('capture', {}).get('fps', 30)
        )
        self.game_detector = GameDetector(config=config)
        
        feature_history = config.get('features', {}).get('feature_history_length', 10)
        cnn_res = tuple(config.get('features', {}).get('cnn_resolution', [80, 60]))
        self.feature_engineer = FeatureEngineer(
            history_length=feature_history,
            cnn_resolution=cnn_res
        )
        self.input_controller = InputController(config=config)
        
        # Load BC model for action mapping
        print(f"Loading action mapping from BC checkpoint: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location='cpu')
        self.action_mapping = checkpoint.get('action_mapping', {})
        self.reverse_action_mapping = {v: k for k, v in self.action_mapping.items()}
        self.num_actions = len(self.action_mapping)
        
        # Action space: Discrete based on BC mapping
        self.action_space = spaces.Discrete(self.num_actions)
        
        # Observation space: Dict with structured (1D) and cnn_frame (2D)
        # Using [1, 60, 80] for PyTorch standard NCHW format natively generated by FeatureEngineer
        self.observation_space = spaces.Dict({
            "structured": spaces.Box(
                low=-np.inf, high=np.inf, 
                shape=(self.feature_engineer.get_structured_dim(),), 
                dtype=np.float32
            ),
            "cnn_frame": spaces.Box(
                low=0.0, high=1.0,
                shape=(1, cnn_res[1], cnn_res[0]),
                dtype=np.float32
            )
        })
        
        # State tracking for reward shaping
        self.last_enemy_dist = None
        self.last_player_health = 1.0
        self.last_enemy_health = 1.0
        
        self.is_dead = False
        self.kill_cooldown = 0
        self.step_count = 0
        
    def _decode_action(self, action_idx: int) -> dict:
        """Convert integer action from PPO to our standard input dictionary"""
        action_str = self.reverse_action_mapping.get(action_idx, "none_0_0_0_0")
        parts = action_str.split('_')
        
        if len(parts) >= 5:
            keys = parts[0].split(',') if parts[0] and parts[0] != 'none' else []
            click_left = parts[1] == '1'
            click_right = parts[2] == '1'
            mouse_dx = int(parts[3])
            mouse_dy = int(parts[4])
            
            return {
                'keys': keys,
                'mouse_dx': mouse_dx * 0.5,
                'mouse_dy': mouse_dy * 0.5,
                'click': click_left,
                'click_left': click_left,
                'click_right': click_right
            }
        return {'keys': [], 'mouse_dx': 0, 'mouse_dy': 0, 'click': False}

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.feature_engineer.reset()
        self.input_controller.reset()
        
        self.last_enemy_dist = None
        self.last_player_health = 1.0
        self.last_enemy_health = 1.0
        
        self.is_dead = False
        self.kill_cooldown = 0
        self.step_count = 0
        self.last_step_time = time.time()
        
        print(f"\n--- NEW EPISODE ---")
        
        # Get initial observation
        frame = self.screen_capture.capture()
        enemies = self.game_detector.detect_enemies(frame)
        in_safe_zone = self.game_detector.detect_safe_zone(frame)
        
        struct, cnn = self.feature_engineer.extract_features(frame, enemies, in_safe_zone)
        
        # Convert cnn from (H, W) to (1, H, W) for Dict space compatibility
        cnn = np.expand_dims(cnn.astype(np.float32) / 255.0, axis=0)
        
        obs = {
            "structured": struct.astype(np.float32),
            "cnn_frame": cnn
        }
        
        return obs, {}

    def step(self, action_idx):
        self.step_count += 1
        
        # Enforce 30 FPS limit to prevent PC from overheating
        target_frame_time = 1.0 / 30.0
        elapsed = time.time() - self.last_step_time
        if elapsed < target_frame_time:
            time.sleep(target_frame_time - elapsed)
        self.last_step_time = time.time()
        
        # 1. Execute Action
        action_dict = self._decode_action(int(action_idx))
        self.input_controller.execute_action(action_dict)
        
        # 2. Get New State
        frame = self.screen_capture.capture()
        enemies = self.game_detector.detect_enemies(frame)
        in_safe_zone = self.game_detector.detect_safe_zone(frame)
        player_health = self.game_detector.detect_player_health(frame)
        
        # Auto-aim (Camera centering on nearest enemy)
        if enemies:
            cx = frame.shape[1] // 2
            cy = frame.shape[0] // 2
            nearest = min(enemies, key=lambda e: np.sqrt((e['player_center'][0] - cx)**2 + (e['player_center'][1] - cy)**2))
            ex, ey = nearest['player_center']
            
            # Normalize delta to [-1.0, 1.0]
            dx = (ex - cx) / cx
            
            # Rotate camera towards enemy
            if abs(dx) > 0.08:
                import pydirectinput as pdi
                # Hold RMB, turn camera, release RMB (works for both Shift Lock and Normal mode)
                pdi.mouseDown(button='right')
                self.input_controller.move_mouse_relative(dx * 0.45, 0.0)
                pdi.mouseUp(button='right')
        
        # Extract features for NN
        struct, cnn = self.feature_engineer.extract_features(frame, enemies, in_safe_zone)
        cnn = np.expand_dims(cnn.astype(np.float32) / 255.0, axis=0)
        
        obs = {
            "structured": struct.astype(np.float32),
            "cnn_frame": cnn
        }
        
        # 3. Reward Shaping
        reward = 0.0
        terminated = False
        truncated = False
        
        # Only run OCR every 30 frames (~1 second) to avoid destroying performance
        if self.step_count % 30 == 0:
            kill_log_status = self.game_detector.detect_kill_log(frame)
            
            # Check for kill (we killed someone) with cooldown
            if self.kill_cooldown > 0:
                self.kill_cooldown -= 1
                
            if kill_log_status['kill'] and self.kill_cooldown == 0:
                reward += 10.0
                self.kill_cooldown = 3  # 3 OCR checks = ~3 seconds cooldown
                victim = kill_log_status.get('victim', 'unknown')
                print(f"\n🩸 KILL! You killed: {victim} (+10 Reward) [Step {self.step_count}]\n")
                
            # Check OCR for death if we missed the health drop
            if kill_log_status['death'] and not self.is_dead:
                reward -= 10.0
                terminated = True
                self.is_dead = True
                killer = kill_log_status.get('killer', 'unknown')
                print(f"\n☠️ KILLED BY: {killer} (-10 Penalty) [Step {self.step_count}]\n")
                
        # Check health for absolute death (falling in void or unlogged deaths)
        if not self.is_dead and player_health < 0.05:
            reward -= 10.0
            terminated = True
            self.is_dead = True
            print(f"\n☠️ DIED! (Fell in void or killed) (-10 Penalty) [Step {self.step_count}]\n")
            
        elif player_health > 0.8:
            # Respawned!
            self.is_dead = False
            
        self.last_player_health = player_health
            
        # Distance tracking logic (hunt reward / cowardice penalty)
        if enemies:
            # Find nearest enemy distance (normalize to screen width)
            cx, cy = frame.shape[1]//2, frame.shape[0]//2
            nearest = min([np.sqrt((e['player_center'][0] - cx)**2 + (e['player_center'][1] - cy)**2) for e in enemies])
            
            if self.last_enemy_dist is not None:
                dist_delta = self.last_enemy_dist - nearest
                if dist_delta > 5: # Moved significantly closer
                    reward += 0.5
                elif dist_delta < -5: # Moved significantly further (cowardice)
                    reward -= 0.01
            
            self.last_enemy_dist = nearest
        else:
            self.last_enemy_dist = None
            
        return obs, reward, terminated, truncated, {}

