"""
Gymnasium Environment for Roblox Sword Fight Bot
Connects the game state to the SB3 PPO algorithm.
"""
import gymnasium as gym
from gymnasium import spaces
import numpy as np
import time
import torch

from feature_extraction.screen_processor import ScreenCapture
from feature_extraction.color_detector import GameDetector
from feature_extraction.feature_engineer import FeatureEngineer
from utils.input_control import InputController

class RobloxGymEnv(gym.Env):
    """
    Standardized Gymnasium environment for Roblox live RL training.
    """
    def __init__(self, config: dict, checkpoint_path: str):
        super(RobloxGymEnv, self).__init__()
        
        self.config = config
        
        # Core components
        self.screen_capture = ScreenCapture(
            resolution=tuple(config.get('capture', {}).get('resolution', [800, 600])),
            fps=config.get('capture', {}).get('fps', 30)
        )
        self.game_detector = GameDetector(config=config)
        
        feature_history = config.get('features', {}).get('feature_history_length', 10)
        cnn_res = tuple(config.get('features', {}).get('cnn_resolution', [80, 60]))
        self.feature_engineer = FeatureEngineer(
            history_length=feature_history,
            cnn_resolution=cnn_res
        )
        self.input_controller = InputController(config=config)
        
        # Load BC model for action mapping
        print(f"Loading action mapping from BC checkpoint: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location='cpu')
        self.action_mapping = checkpoint.get('action_mapping', {})
        self.reverse_action_mapping = {v: k for k, v in self.action_mapping.items()}
        self.num_actions = len(self.action_mapping)
        
        # Action space: Discrete based on BC mapping
        self.action_space = spaces.Discrete(self.num_actions)
        
        # Observation space: Dict with structured (1D) and cnn_frame (2D)
        # Using [1, 60, 80] for PyTorch standard NCHW format natively generated by FeatureEngineer
        self.observation_space = spaces.Dict({
            "structured": spaces.Box(
                low=-np.inf, high=np.inf, 
                shape=(self.feature_engineer.get_structured_dim(),), 
                dtype=np.float32
            ),
            "cnn_frame": spaces.Box(
                low=0.0, high=1.0,
                shape=(1, cnn_res[1], cnn_res[0]),
                dtype=np.float32
            )
        })
        
        # State tracking for reward shaping
        self.last_enemy_dist = None
        self.last_player_health = 1.0
        self.last_enemy_health = 1.0
        
    def _decode_action(self, action_idx: int) -> dict:
        """Convert integer action from PPO to our standard input dictionary"""
        action_str = self.reverse_action_mapping.get(action_idx, "none_0_0_0_0")
        parts = action_str.split('_')
        
        if len(parts) >= 5:
            keys = parts[0].split(',') if parts[0] and parts[0] != 'none' else []
            click_left = parts[1] == '1'
            click_right = parts[2] == '1'
            mouse_dx = int(parts[3])
            mouse_dy = int(parts[4])
            
            return {
                'keys': keys,
                'mouse_dx': mouse_dx * 0.5,
                'mouse_dy': mouse_dy * 0.5,
                'click': click_left,
                'click_left': click_left,
                'click_right': click_right
            }
        return {'keys': [], 'mouse_dx': 0, 'mouse_dy': 0, 'click': False}

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.feature_engineer.reset()
        self.input_controller.reset()
        
        self.last_enemy_dist = None
        self.last_player_health = 1.0
        self.last_enemy_health = 1.0
        
        # Get initial observation
        frame = self.screen_capture.capture()
        enemies = self.game_detector.detect_enemies(frame)
        in_safe_zone = self.game_detector.detect_safe_zone(frame)
        
        struct, cnn = self.feature_engineer.extract_features(frame, enemies, in_safe_zone)
        
        # Convert cnn from (H, W) to (1, H, W) for Dict space compatibility
        cnn = np.expand_dims(cnn.astype(np.float32) / 255.0, axis=0)
        
        obs = {
            "structured": struct.astype(np.float32),
            "cnn_frame": cnn
        }
        
        return obs, {}

    def step(self, action_idx):
        # 1. Execute Action
        action_dict = self._decode_action(int(action_idx))
        self.input_controller.execute_action(action_dict)
        
        # DEBUG PRINTS FOR USER
        if '1' in action_dict['keys'] or action_dict['click_left']:
            print(f"🗡️ Action: Keys={action_dict['keys']} | Left Click={action_dict['click_left']}")
        
        # 2. Get New State
        frame = self.screen_capture.capture()
        enemies = self.game_detector.detect_enemies(frame)
        in_safe_zone = self.game_detector.detect_safe_zone(frame)
        player_health = self.game_detector.detect_player_health(frame)
        kill_log_detected = self.game_detector.detect_kill_log(frame)
        
        # Extract features for NN
        struct, cnn = self.feature_engineer.extract_features(frame, enemies, in_safe_zone)
        cnn = np.expand_dims(cnn.astype(np.float32) / 255.0, axis=0)
        
        obs = {
            "structured": struct.astype(np.float32),
            "cnn_frame": cnn
        }
        
        # 3. Reward Shaping
        reward = 0.0
        terminated = False
        truncated = False
        
        # Penalty for player damage or death
        if player_health < self.last_player_health:
            reward -= 5.0
            print(f"💀 DAMAGE TAKEN! Health dropped to {player_health:.2f} (-5 Penalty)")
            if player_health < 0.1:
                terminated = True
                print(f"☠️ DIED! Episode terminated.")
        self.last_player_health = player_health
        
        # Huge reward for a kill
        if kill_log_detected:
            reward += 10.0
            print("🩸 KILL CONFIRMED! ⏰ (+10 Reward)")
            
        # Distance tracking logic (hunt reward / cowardice penalty)
        if enemies:
            # Find nearest enemy distance (normalize to screen width)
            cx, cy = frame.shape[1]//2, frame.shape[0]//2
            nearest = min([np.sqrt((e['player_center'][0] - cx)**2 + (e['player_center'][1] - cy)**2) for e in enemies])
            
            if self.last_enemy_dist is not None:
                dist_delta = self.last_enemy_dist - nearest
                if dist_delta > 5: # Moved significantly closer
                    reward += 0.5
                elif dist_delta < -5: # Moved significantly further (cowardice)
                    reward -= 0.01
            
            self.last_enemy_dist = nearest
        else:
            self.last_enemy_dist = None
            
        return obs, reward, terminated, truncated, {}
